// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlhy9870oESCR-2kHbLQATIJAyuJvl8z4',
    appId: '1:293817589861:android:8617e9b5f5398a542e268c',
    messagingSenderId: '293817589861',
    projectId: 'little-heroes-22f73',
    storageBucket: 'little-heroes-22f73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bI3QyrZiaQR7bllnPonO1GfBA9zvxBQ',
    appId: '1:293817589861:ios:db62a66357e02a422e268c',
    messagingSenderId: '293817589861',
    projectId: 'little-heroes-22f73',
    storageBucket: 'little-heroes-22f73.firebasestorage.app',
    iosBundleId: 'com.robotech.little-heroes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_bI3QyrZiaQR7bllnPonO1GfBA9zvxBQ',
    appId: '1:293817589861:ios:075734912469f3282e268c',
    messagingSenderId: '293817589861',
    projectId: 'little-heroes-22f73',
    storageBucket: 'little-heroes-22f73.firebasestorage.app',
    iosBundleId: 'com.example.littleHeroesMobile',
  );
}
